# Day 4: Pandas - Tabular Data Analysis

## Learning Objectives

By the end of this notebook, i will be able to:
- Understand the difference between Series and DataFrame.
- Load and inspect datasets using Pandas.
- Select and filter data using different techniques.
- Handle misssing values and duplicates.
- Perform grouping and aggregation operations.

# Introduction to Pandas

Pandas is a python library designed for data manipulation and analysis.

It provides powerful data structures such as Series and DataFrames, Wich make working with structured data easier.

Pandas is widely used in Data Science workflows before applying Machine Learning models.

# Why Pandas?

Although Python lists can store data, they become difficult to manage when datasets grow larger.

Pandas solves this problem by providing:

- Easy loading of datasets from different file formats.
- Fast manipulation of rows and columns.
- Automatic handling of missing values.
- Powerful filtering and grouping operations.
- Built-in statistical functions.
- Integration with NumPy, Matplotlib, Scikit-learn, TensorFlow, and many other libraries.

Because of these features, Pandas has become the standard library for data analysis in Python.

## Import Pandas

In [1]:
import pandas as pd

# Series vs DataFrame

A series represents a single labeled column, while a DataFrame represents a complete table containing multiple rows and columns.

In [2]:
series_example = pd.Series([10, 20, 30])
print(series_example)

0    10
1    20
2    30
dtype: int64

In [5]:
# DataFrame example
data = {
    "Name" : ["Ali", "Sara", "Omar"],
    "Age" : [22, 25, 30]
}

df = pd.DataFrame(data)

df

   Name  Age
0   Ali   22
1  Sara   25
2  Omar   30

# Loading Data

Most real-world datasets are stored in files such as CSV.

Pandas provides read_csv() to load these datasets into a DataFrame.

In [6]:
data = {
    "Name" : ["Ali", "Sara", "Omar", "Lina"],
    "Age" : [22, 25, 30, 28],
    "Income" : [4000, 6000, 8000, 7000]
}

df = pd.DataFrame(data)

df

   Name  Age  Income
0   Ali   22    4000
1  Sara   25    6000
2  Omar   30    8000
3  Lina   28    7000

# Inspecting Dataset

In [7]:
df.head()

   Name  Age  Income
0   Ali   22    4000
1  Sara   25    6000
2  Omar   30    8000
3  Lina   28    7000

## head()

The `head()` function displays the first five rows of a dataset by default.

It is commonly used immediately after loading a dataset to verify that the data has been read correctly.

#### Note

Passing a number to `head()` changes the number of displayed rows.

For example:
- `head(3)` -> first 3 rows.
- `head(10)` -> first 10 rows.

## tail()

The `tail()` function displays thr last five rows of the dataset.

This is useful checking whether the dataset was loaded completely or for inpecting the final records.

# Dataset Dimensions

In [10]:
df.shape

(4, 3)

## shape

The `shape` attribute return a tuple in the following format:

(rows, columns)

For example: 
(1000, 12)

- 1000 rows (observations)
- 12 columns (features)

Knowing the size of a dataset is often the first step before analysis.

In [11]:
df.columns

Index(['Name', 'Age', 'Income'], dtype='str')

## columns

The `columns` attribute returns the names of all columns in the DataFrame.

Column names are essential because they are used later when selecting, filtering, grouping, or modifying data.

In [12]:
df.dtypes

Name        str
Age       int64
Income    int64
dtype: object

## dtypes

The `dtypes` attribute displays the data type of each column.

Common data types include:

- int64 → Integer numbers
- float64 → Decimal numbers
- object → Text values
- bool → Boolean values (True/False)

Understanding data types is important because many operations depend on them.

In [13]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      str
 1   Age     4 non-null      int64
 2   Income  4 non-null      int64
dtypes: int64(2), str(1)
memory usage: 228.0 bytes

## info()

The `info()` function provides a quick overview of the dataset.

It displays:

- Number of rows
- Number of columns
- Column names
- Data types
- Number of non-missing values
- Memory usage

It is one of the most frequently used functions in Pandas because it immediately reveals the structure of the dataset.

In [15]:
df.describe()

         Age       Income
count   4.00     4.000000
mean   26.25  6250.000000
std     3.50  1707.825128
min    22.00  4000.000000
25%    24.25  5500.000000
50%    26.50  6500.000000
75%    28.50  7250.000000
max    30.00  8000.000000

## describe()

The `describe()` function generates descriptive statistics for numerical columns.

It includes:

- count → Number of non-missing values
- mean → Average value
- std → Standard deviation
- min → Minimum value
- 25% → First quartile
- 50% → Median
- 75% → Third quartile
- max → Maximum value

These statistics provide a quick understanding of the numerical distribution of the dataset.

# Summary

At this stage, we have learned how to:

- Load a dataset from a CSV file.
- Preview the first and last rows.
- Check the dataset dimensions.
- Display column names.
- Inspect data types.
- Obtain detailed dataset information.
- Generate descriptive statistics.

These inspection steps should always be performed before cleaning or analyzing any dataset.

# Selecting Data from a DataFrame

After loading and inspecting a dataset, the next step is accessing specific parts of the data.

Pandas provides flexible ways to select:

- Individual columns.
- Multiple columns.
- Specific rows.
- Rows that satisfy certain conditions.

Selecting data correctly is essential because almost every data analysis task requires extracting specific information from a dataset.

# Selecting Columns

Columns in a DataFrame represent features or attributes.

Pandas allows selecting columns using their names.

The result depends on whether we select one column or multiple columns.

In [16]:
df["Age"]

0    22
1    25
2    30
3    28
Name: Age, dtype: int64

## Selecting a Single Column

When selecting one column, Pandas returns a Series.

Example:

```python
df["Age"]
```

returns only the Age column with its index.

In [17]:
type(df["Age"])

pandas.Series

The output is:

`pandas.Series`

because a single column represents a one-dimensional structure.

In [19]:
df[["Age", "Income"]]

   Age  Income
0   22    4000
1   25    6000
2   30    8000
3   28    7000

## Selecting Multiple Columns

To select multiple columns, we pass a list of column names.

Example:

```python
df[["Age", "Income"]]
```

The output is a DataFrame because multiple columns create a two-dimensional table.

# Filtering Rows

Filtering means selecting rows based on a condition.

The condition creates a Boolean mask containing:

- True → keep the row
- False → remove the row

This concept is similar to Boolean masking in NumPy.

In [22]:
df["Age"] > 25

0    False
1    False
2     True
3     True
Name: Age, dtype: bool

The expression above does not return the filtered data directly.

Instead, it creates a Boolean Series that tells Pandas which rows satisfy the condition.

In [23]:
df[df["Age"] > 25]

   Name  Age  Income
2  Omar   30    8000
3  Lina   28    7000

The DataFrame now contains only rows where the Age value is greater than 25.

This technique is one of the most commonly used operations in data analysis.

# Filtering with Multiple Conditions

Sometimes we need more than one condition.

For example:

Select students who are older than 20 and have an income greater than 5000.

In [24]:
df[(df["Age"] > 20) & (df["Income"] > 5000)]

   Name  Age  Income
1  Sara   25    6000
2  Omar   30    8000
3  Lina   28    7000

## Logical Operators in Pandas

| Operator | Meaning |
|---|---|
| & | AND |
| \| | OR |
| ~ | NOT |

Important:

Each condition must be surrounded by parentheses.

In [25]:
df[(df["Age"] > 25) | (df["Income"] > 7000)]

   Name  Age  Income
2  Omar   30    8000
3  Lina   28    7000

The OR operator (`|`) returns rows where at least one condition is True.

# Selecting Data Using loc and iloc

Pandas provides two powerful indexers:

- `loc` → label-based selection
- `iloc` → position-based selection

They are useful when we need more control over selecting rows and columns.

# loc

`loc` selects data using row and column labels.

The general syntax:

```python
df.loc[row_selection, column_selection]
```

In [27]:
df.loc[0]

Name       Ali
Age         22
Income    4000
Name: 0, dtype: object

This returns the row with index label 0.

In [28]:
df.loc[0, "Name"]

'Ali'

This selects:

- Row with label 0
- Column "Name"

The result is a single value.

In [29]:
df.loc[df["Age"] > 25, "Income"]

2    8000
3    7000
Name: Income, dtype: int64

This means:

"Select the Income values for rows where Age is greater than 25."

`loc` is very useful when combining filtering with column selection.

# iloc

`iloc` selects data using integer positions.

It works like normal Python indexing.

The syntax:

```python
df.iloc[row_position, column_position]
```

In [30]:
df.iloc[0,1]

np.int64(22)

This selects:

- First row (position 0)
- Second column (position 1)

Remember that indexing starts from zero.

# loc vs iloc

| loc | iloc |
|---|---|
| Uses labels | Uses positions |
| Uses column names | Uses column numbers |
| More readable | Similar to Python lists |
| Good for conditions | Good for fixed positions |

# Best Practices

- Prefer column names instead of positions when possible because they are easier to understand.
- Use `loc` when working with conditions.
- Use `iloc` when you specifically need rows or columns by position.
- Always check column names before selecting data.

# Data Cleaning

Real-world datasets often contain problems such as:

- Missing values.
- Duplicate records.
- Incorrect data types.
- Inconsistent values.

Before performing analysis or building Machine Learning models, these issues must be handled carefully.

Data cleaning improves data quality and ensures more reliable results.

# Why is Data Cleaning Important?

Machine Learning models learn from the data they receive.

If the dataset contains errors, missing information, or incorrect formats, the model may learn wrong patterns and produce inaccurate predictions.

Therefore, cleaning and preparing data is a critical step in every Data Science workflow.

# Handling Missing Values

A missing value means that some information is not available.

For example:

| Name | Age | Income |
|---|---|---|
| Ali | 20 | 5000 |
| Sara | NaN | 6000 |

The missing value is represented by `NaN` (Not a Number).

In [31]:
df.isnull()

    Name    Age  Income
0  False  False   False
1  False  False   False
2  False  False   False
3  False  False   False

## isnull()

The `isnull()` function checks every value in the DataFrame.

It returns:

- True → value is missing
- False → value exists

However, for large datasets, viewing the entire output is not practical.

In [32]:
df.isnull().sum()

Name      0
Age       0
Income    0
dtype: int64

The combination:

```python
df.isnull().sum()
```

is commonly used to count missing values in each column.

It helps identify which columns require cleaning.

# Creating Missing Values for Practice

To understand how missing values are handled, we can create an example.

In [33]:
df.loc[1, "Age"] = None

df

   Name   Age  Income
0   Ali  22.0    4000
1  Sara   NaN    6000
2  Omar  30.0    8000
3  Lina  28.0    7000

In [34]:
df.isnull().sum()

Name      0
Age       1
Income    0
dtype: int64

# Filling Missing Values

One approach to handle missing values is replacing them with a meaningful value.

For numerical columns, a common choice is the mean (average).

In [36]:
df["Age"].fillna(df["Age"].mean())

0    22.000000
1    26.666667
2    30.000000
3    28.000000
Name: Age, dtype: float64

## fillna()

`fillna()` replaces missing values with a specified value.

Examples:

- Mean → for numerical data
- Median → when data contains outliers
- Mode → for categorical data

Choosing the replacement method depends on the nature of the dataset.

In [40]:
df

   Name   Age  Income
0   Ali  22.0    4000
1  Sara   NaN    6000
2  Omar  30.0    8000
3  Lina  28.0    7000

# Removing Missing Values

Sometimes filling missing values is not the best solution.

If a row contains too much missing information, it may be better to remove it.

In [41]:
df.dropna()

   Name   Age  Income
0   Ali  22.0    4000
2  Omar  30.0    8000
3  Lina  28.0    7000

## dropna()

The `dropna()` function removes rows containing missing values.

Example:

Before:

| Name | Age |
|---|---|
| Ali | 20 |
| Sara | NaN |

After `dropna()`:

| Name | Age |
|---|---|
| Ali | 20 |

## fillna() vs dropna()

| Method | Usage |
|---|---|
| fillna() | Replace missing values |
| dropna() | Remove missing rows |

The decision depends on the dataset and the importance of the missing information.

# Best Practices for Missing Values

Before handling missing values:

1. Identify how many values are missing.
2. Understand why they are missing.
3. Decide whether to fill or remove them.
4. Document the decision.

Never remove missing data without understanding its impact.

# Handling Duplicate Data

Duplicate rows are repeated records in a dataset.

They can affect analysis by giving some observations more importance than others.

Pandas provides functions to detect and remove duplicates.

In [43]:
df.duplicated()

0    False
1    False
2    False
3    False
dtype: bool

## duplicated()

Returns:

- True → duplicated row
- False → unique row

It is useful before removing duplicates to understand the dataset.

In [45]:
df.drop_duplicates()

   Name   Age  Income
0   Ali  22.0    4000
1  Sara   NaN    6000
2  Omar  30.0    8000
3  Lina  28.0    7000

# Data Cleaning Summary

In this section, we learned how to:

- Detect missing values using `isnull()`.
- Count missing values with `sum()`.
- Replace missing values using `fillna()`.
- Remove incomplete rows using `dropna()`.
- Detect and remove duplicate records.
- Convert column data types using `astype()`.

Cleaning data is a fundamental step before visualization and Machine Learning.

# Grouping Data with groupby()

Often, we need to analyze data based on categories or groups.

For example:

- Average income per department.
- Total sales per product category.
- Maximum score per class.

Pandas provides the `groupby()` function to perform these operations efficiently.

# The Split-Apply-Combine Concept

The idea behind `groupby()` is based on three steps:

1. Split:
   Divide the data into groups based on a column.

2. Apply:
   Perform an operation on each group.

3. Combine:
   Combine the results into a new DataFrame or Series.

This approach is known as:

**Split → Apply → Combine**

Example:

Imagine we have student data:

| Name | Department | Score |
|---|---|---|
| Ali | AI | 90 |
| Sara | CS | 85 |
| Omar | AI | 95 |

We can group students by department and calculate the average score.

In [49]:
data = {
    "Name": ["Ali", "Sara", "Omar", "Lina"],
    "Department": ["AI", "CS", "AI", "CS"],
    "Score": [90, 85, 95, 80]
}

students = pd.DataFrame(data)

students

   Name Department  Score
0   Ali         AI     90
1  Sara         CS     85
2  Omar         AI     95
3  Lina         CS     80

In [50]:
students.groupby("Department")["Score"].mean()

Department
AI    92.5
CS    82.5
Name: Score, dtype: float64

## Understanding the Code

```python
students.groupby("Department")["Score"].mean()
```

Step by step:

1. `groupby("Department")`
   
   Creates groups based on department.

2. `["Score"]`

   Selects the column we want to analyze.

3. `.mean()`

   Calculates the average score for each group.

The output shows:

- Average score for AI students.
- Average score for CS students.

This allows us to compare patterns between different groups.

# Common Aggregation Functions

Aggregation means applying a calculation to each group.

Common aggregation functions include:

| Function | Description |
|---|---|
| mean() | Average value |
| sum() | Total value |
| count() | Number of values |
| max() | Maximum value |
| min() | Minimum value |

In [51]:
students.groupby("Department")["Score"].max()

Department
AI    95
CS    85
Name: Score, dtype: int64

In [52]:
students.groupby("Department")["Score"].count()

Department
AI    2
CS    2
Name: Score, dtype: int64

# Multiple Aggregations Using agg()

Sometimes we want to apply different calculations to multiple columns.

The `agg()` function allows us to define several aggregation operations at once.

In [53]:
students.groupby("Department").agg(
    {
        "Score": ["mean", "max", "min"]
    }
)

           Score
            mean max min
Department
AI          92.5  95  90
CS          82.5  85  80

The result contains multiple statistics for each department.

This is useful when performing deeper analysis instead of looking at only one value.

In [54]:
students.groupby("Department").agg(
    {
        "Score": "mean"
    }
)

            Score
Department
AI           92.5
CS           82.5

# Practical Example

In real datasets, we might answer questions like:

- What is the average salary for each job category?
- Which product category generates the highest sales?
- What is the maximum value in each group?

GroupBy helps discover patterns and relationships inside data.

# GroupBy Best Practices

- Always understand the meaning of the grouping column.
- Choose aggregation functions that match the analysis goal.
- Check the result after grouping.
- Avoid grouping by columns with too many unique values unless necessary.

# Hands-on Lab: Exploring a Real Dataset with Pandas

In this lab, I will apply the Pandas concepts learned in this notebook using a real dataset.

The workflow includes:

1. Loading the dataset.
2. Exploring its structure.
3. Handling missing values.
4. Filtering data.
5. Performing grouped analysis.

In [62]:
import pandas as pd

df = pd.read_csv("Students_Courses.csv")

In [69]:
df.head()

   StudentID  Name  StudyTime  Score         Level Completed      City
0        801   Ali        2.0   70.0      Beginner       Yes    Nablus
1        802  Sara        5.0   85.0      beginner       Yes  Ramallah
2        803  Omar        NaN   60.0  Intermediate        No    nablus
3        804  Lina       10.0  150.0      Advanced       Yes     Jenin
4        805  Noor       -3.0   40.0  Intermediate        No     Jenin

In [70]:
df.shape

(12, 7)

In [71]:
df.columns

Index(['StudentID', 'Name', 'StudyTime', 'Score', 'Level', 'Completed',
       'City'],
      dtype='str')

In [72]:
df.dtypes

StudentID      int64
Name             str
StudyTime    float64
Score        float64
Level            str
Completed        str
City             str
dtype: object

In [74]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   StudentID  12 non-null     int64
 1   Name       12 non-null     str
 2   StudyTime  11 non-null     float64
 3   Score      11 non-null     float64
 4   Level      12 non-null     str
 5   Completed  12 non-null     str
 6   City       12 non-null     str
dtypes: float64(2), int64(1), str(4)
memory usage: 804.0 bytes

In [75]:
df.describe()

        StudentID  StudyTime       Score
count   12.000000  11.000000   11.000000
mean   806.500000   4.181818   78.000000
std      3.605551   4.238353   29.189039
min    801.000000  -3.000000   40.000000
25%    803.750000   2.000000   62.500000
50%    806.500000   4.000000   70.000000
75%    809.250000   5.500000   86.500000
max    812.000000  12.000000  150.000000

### Observation

The dataset contains information about students enrolled in online courses.

It includes:

- Student ID
- Student name
- Study time
- Score
- Course level
- Completion status
- City

The dataset contains both numerical and categorical features.

## Step 2: Check Missing Values

In [73]:
df.isnull().sum()

StudentID    0
Name         0
StudyTime    1
Score        1
Level        0
Completed    0
City         0
dtype: int64

### Justification

The dataset contains missing values in the **StudyTime** and **Score** columns.

Since both columns contain numerical values, replacing the missing values with the column mean is a reasonable choice. This preserves the number of records while providing an estimated value based on the existing data.

In [76]:
df["StudyTime"] = df["StudyTime"].fillna(df["StudyTime"].mean())
df["Score"] = df["Score"].fillna(df["Score"].mean())

In [77]:
df.isnull().sum()

StudentID    0
Name         0
StudyTime    0
Score        0
Level        0
Completed    0
City         0
dtype: int64

# Step 3: Filter the Dataset

In this example, I will filter students who scored more than **80**.

In [78]:
high_score_students = df[df["Score"] > 80]

high_score_students

    StudentID    Name  StudyTime  Score     Level Completed      City
1         802    Sara        5.0   85.0  beginner       Yes  Ramallah
3         804    Lina       10.0  150.0  Advanced       Yes     Jenin
7         808    Huda        4.0   88.0  ADVANCED       yes    hebron
9         810  Yousef       12.0   95.0  Advanced       Yes  Ramallah
11        812  Kareem        5.0   85.0  Beginner       Yes  Ramallah

### Observation

The filtered dataset contains students with scores greater than 80.

This subset represents high-performing students and could be useful for further performance analysis.

# Step 4: Group and Analyze Data

I will calculate the average score for each course level using `groupby()`.

In [79]:
df.groupby("Level")["Score"].mean()

Level
ADVANCED         88.00
Advanced        122.50
Beginner         68.75
Intermediate     55.00
advanced         78.00
beginner         85.00
Name: Score, dtype: float64

### Interpretation

Grouping the data by course level makes it easier to compare student performance across different learning levels.

This type of analysis helps summarize the data and identify trends within each category.

# Bonus: Data Quality Check

While exploring the dataset, I noticed some data quality issues that are common in real-world datasets.

In [80]:
df["Level"].unique()

<StringArray>
['Beginner', 'beginner', 'Intermediate', 'Advanced', 'advanced', 'ADVANCED']
Length: 6, dtype: str

In [84]:
df["Level"] = df["Level"].str.title()

df["Level"].unique()

<StringArray>
['Beginner', 'Intermediate', 'Advanced']
Length: 3, dtype: str

The values **"Beginner"** and **"beginner"** refer to the same category.

Using `str.title()` standardizes the capitalization and prevents duplicate categories.

In [81]:
df["City"].unique()

<StringArray>
[  'Nablus', 'Ramallah',   'nablus',    'Jenin',   'Hebron',   'hebron',
  'Tulkarm',  'Jericho']
Length: 8, dtype: str

In [85]:
df["City"] = df["City"].str.title()

df["City"].unique()

<StringArray>
['Nablus', 'Ramallah', 'Jenin', 'Hebron', 'Tulkarm', 'Jericho']
Length: 6, dtype: str

City names should have consistent formatting.

Standardizing capitalization ensures that cities with different letter cases are treated as the same value.

In [82]:
df[df["Score"] > 100]

   StudentID  Name  StudyTime  Score     Level Completed   City
3        804  Lina       10.0  150.0  Advanced       Yes  Jenin

Exam scores should normally range between 0 and 100.

Values outside this range are considered invalid.

In [86]:
df = df[df["Score"] <= 100]

In [87]:
df["Score"].max()

np.float64(95.0)

In [88]:
df[df["StudyTime"] < 0]

   StudentID  Name  StudyTime  Score         Level Completed   City
4        805  Noor       -3.0   40.0  Intermediate        No  Jenin

Study time cannot be negative.

Negative values most likely result from data entry errors.

In [89]:
df = df[df["StudyTime"] >= 0]

In [90]:
df["StudyTime"].min()

np.float64(0.0)

# Bonus: Data Preprocessing

Before using the dataset for Machine Learning, additional preprocessing steps can improve data quality and consistency.

## Encoding

In [94]:
df["Completed"].unique()

<StringArray>
['Yes', 'No', 'yes']
Length: 3, dtype: str

In [101]:
df["Completed"] = df["Completed"].map({
    "Yes": 1,
    "No": 0
})

In [103]:
df["StudyTime"] = (
    df["StudyTime"] - df["StudyTime"].min()
) / (
    df["StudyTime"].max() - df["StudyTime"].min()
)

In [104]:
df["Score"] = (
    df["Score"] - df["Score"].min()
) / (
    df["Score"].max() - df["Score"].min()
)

In [107]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

df[["StudyTime", "Score"]] = scaler.fit_transform(
    df[["StudyTime", "Score"]]
)

## Check the Cleaned Dataset

In [110]:
df.head()

,StudentID,Name,StudyTime,Score,Completed,City,Level_Advanced,Level_Beginner,Level_Intermediate
0,801,Ali,0.166667,0.444444,NaN,Nablus,0,1,0
1,802,Sara,0.416667,0.777778,NaN,Ramallah,0,1,0
2,803,Omar,0.348485,0.222222,NaN,Nablus,0,0,1
5,806,Ali,0.166667,0.444444,NaN,Nablus,0,1,0
6,807,Ahmad,0.500000,0.622222,NaN,Hebron,1,0,0

In [111]:
df.info()

<class 'pandas.DataFrame'>
Index: 10 entries, 0 to 11
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   StudentID           10 non-null     int64
 1   Name                10 non-null     str
 2   StudyTime           10 non-null     float64
 3   Score               10 non-null     float64
 4   Completed           0 non-null      float64
 5   City                10 non-null     str
 6   Level_Advanced      10 non-null     int64
 7   Level_Beginner      10 non-null     int64
 8   Level_Intermediate  10 non-null     int64
dtypes: float64(3), int64(4), str(2)
memory usage: 800.0 bytes

In [112]:
df.describe()

,StudentID,StudyTime,Score,Completed,Level_Advanced,Level_Beginner,Level_Intermediate
count,10.000000,10.000000,10.000000,0.0,10.000000,10.000000,10.000000
mean,806.900000,0.359848,0.546667,NaN,0.300000,0.500000,0.200000
std,3.842742,0.269345,0.312203,NaN,0.483046,0.527046,0.421637
min,801.000000,0.000000,0.000000,NaN,0.000000,0.000000,0.000000
25%,803.750000,0.187500,0.361111,NaN,0.000000,0.000000,0.000000
50%,807.500000,0.340909,0.533333,NaN,0.000000,0.500000,0.000000
75%,809.750000,0.416667,0.777778,NaN,0.750000,1.000000,0.000000
max,812.000000,1.000000,1.000000,NaN,1.000000,1.000000,1.000000

# Conclusion

In this notebook, I explored the fundamentals of Pandas for working with tabular data.

I learned how to:

- Create and understand Series and DataFrames.
- Load and inspect datasets.
- Select and filter data efficiently.
- Handle missing values and duplicates.
- Convert data types.
- Perform grouping and aggregation operations.

These techniques are essential for preparing datasets before visualization and Machine Learning tasks.

# Key Takeaways

- Data understanding comes before analysis.
- Cleaning data is a major part of real-world Data Science.
- Pandas provides powerful tools for manipulating structured data.
- Proper data preparation improves the quality of Machine Learning models.